import { Game } from "@/models/game";

// Mock data
export const mockGames: Game[] = [
  {
    id: "1",
    homeTeam: { id: "DET", name: "Lions", abbreviation: "DET" },
    awayTeam: { id: "CHI", name: "Bears", abbreviation: "CHI" },
    startTime: "2023-11-10T19:20:00.000Z",
    status: "upcoming",
    odds: { spread: -6 },
  },
  {
    id: "2",
    homeTeam: { id: "GB", name: "Packers", abbreviation: "GB" },
    awayTeam: { id: "MIN", name: "Vikings", abbreviation: "MIN" },
    startTime: "2023-11-10T16:00:00.000Z",
    status: "live",
    odds: { spread: 3 },
  },
  {
    id: "3",
    homeTeam: { id: "KC", name: "Chiefs", abbreviation: "KC" },
    awayTeam: { id: "DEN", name: "Broncos", abbreviation: "DEN" },
    startTime: "2023-11-09T20:15:00.000Z",
    status: "completed",
    odds: { spread: -7.5 },
  },
  {
    id: "4",
    homeTeam: { id: "BUF", name: "Bills", abbreviation: "BUF" },
    awayTeam: { id: "NYJ", name: "Jets", abbreviation: "NYJ" },
    startTime: "2023-11-12T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -9 },
  },
  {
    id: "5",
    homeTeam: { id: "DAL", name: "Cowboys", abbreviation: "DAL" },
    awayTeam: { id: "NYG", name: "Giants", abbreviation: "NYG" },
    startTime: "2023-11-12T16:25:00.000Z",
    status: "upcoming",
    odds: { spread: -10.5 },
  },
  {
    id: "6",
    homeTeam: { id: "BAL", name: "Ravens", abbreviation: "BAL" },
    awayTeam: { id: "CLE", name: "Browns", abbreviation: "CLE" },
    startTime: "2023-11-12T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -3 },
  },
  {
    id: "7",
    homeTeam: { id: "SF", name: "49ers", abbreviation: "SF" },
    awayTeam: { id: "SEA", name: "Seahawks", abbreviation: "SEA" },
    startTime: "2023-11-12T20:20:00.000Z",
    status: "upcoming",
    odds: { spread: -6.5 },
  },
  {
    id: "8",
    homeTeam: { id: "PHI", name: "Eagles", abbreviation: "PHI" },
    awayTeam: { id: "WAS", name: "Commanders", abbreviation: "WAS" },
    startTime: "2023-11-12T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -8 },
  },
  {
    id: "9",
    homeTeam: { id: "MIA", name: "Dolphins", abbreviation: "MIA" },
    awayTeam: { id: "LV", name: "Raiders", abbreviation: "LV" },
    startTime: "2023-11-12T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -12 },
  },
  {
    id: "10",
    homeTeam: { id: "LAC", name: "Chargers", abbreviation: "LAC" },
    awayTeam: { id: "NE", name: "Patriots", abbreviation: "NE" },
    startTime: "2023-11-12T16:05:00.000Z",
    status: "upcoming",
    odds: { spread: -4.5 },
  },
  {
    id: "11",
    homeTeam: { id: "TEN", name: "Titans", abbreviation: "TEN" },
    awayTeam: { id: "TB", name: "Buccaneers", abbreviation: "TB" },
    startTime: "2023-11-12T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: 1.5 },
  },
  {
    id: "12",
    homeTeam: { id: "ATL", name: "Falcons", abbreviation: "ATL" },
    awayTeam: { id: "ARI", name: "Cardinals", abbreviation: "ARI" },
    startTime: "2023-11-12T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -3 },
  },
  {
    id: "13",
    homeTeam: { id: "NO", name: "Saints", abbreviation: "NO" },
    awayTeam: { id: "CAR", name: "Panthers", abbreviation: "CAR" },
    startTime: "2023-11-12T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -7 },
  },
  {
    id: "14",
    homeTeam: { id: "HOU", name: "Texans", abbreviation: "HOU" },
    awayTeam: { id: "CIN", name: "Bengals", abbreviation: "CIN" },
    startTime: "2023-11-12T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: 2.5 },
  },
  {
    id: "15",
    homeTeam: { id: "IND", name: "Colts", abbreviation: "IND" },
    awayTeam: { id: "PIT", name: "Steelers", abbreviation: "PIT" },
    startTime: "2023-11-12T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -1 },
  },
  {
    id: "16",
    homeTeam: { id: "JAX", name: "Jaguars", abbreviation: "JAX" },
    awayTeam: { id: "TEN", name: "Titans", abbreviation: "TEN" },
    startTime: "2023-11-19T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -4 },
  },
  {
    id: "17",
    homeTeam: { id: "DEN", name: "Broncos", abbreviation: "DEN" },
    awayTeam: { id: "MIN", name: "Vikings", abbreviation: "MIN" },
    startTime: "2023-11-19T16:05:00.000Z",
    status: "upcoming",
    odds: { spread: 1.5 },
  },
  {
    id: "18",
    homeTeam: { id: "LV", name: "Raiders", abbreviation: "LV" },
    awayTeam: { id: "MIA", name: "Dolphins", abbreviation: "MIA" },
    startTime: "2023-11-19T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: 6 },
  },
  {
    id: "19",
    homeTeam: { id: "NYG", name: "Giants", abbreviation: "NYG" },
    awayTeam: { id: "WAS", name: "Commanders", abbreviation: "WAS" },
    startTime: "2023-11-19T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -2.5 },
  },
  {
    id: "20",
    homeTeam: { id: "CHI", name: "Bears", abbreviation: "CHI" },
    awayTeam: { id: "DET", name: "Lions", abbreviation: "DET" },
    startTime: "2023-11-19T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: 3 },
  },
  {
    id: "21",
    homeTeam: { id: "CLE", name: "Browns", abbreviation: "CLE" },
    awayTeam: { id: "PIT", name: "Steelers", abbreviation: "PIT" },
    startTime: "2023-11-19T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -2 },
  },
  {
    id: "22",
    homeTeam: { id: "LAR", name: "Rams", abbreviation: "LAR" },
    awayTeam: { id: "SEA", name: "Seahawks", abbreviation: "SEA" },
    startTime: "2023-11-19T16:05:00.000Z",
    status: "upcoming",
    odds: { spread: 1 },
  },
  {
    id: "23",
    homeTeam: { id: "ARI", name: "Cardinals", abbreviation: "ARI" },
    awayTeam: { id: "HOU", name: "Texans", abbreviation: "HOU" },
    startTime: "2023-11-19T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -1.5 },
  },
  {
    id: "24",
    homeTeam: { id: "CAR", name: "Panthers", abbreviation: "CAR" },
    awayTeam: { id: "DAL", name: "Cowboys", abbreviation: "DAL" },
    startTime: "2023-11-19T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: 10.5 },
  },
  {
    id: "25",
    homeTeam: { id: "TB", name: "Buccaneers", abbreviation: "TB" },
    awayTeam: { id: "SF", name: "49ers", abbreviation: "SF" },
    startTime: "2023-11-19T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: 6 },
  },
  {
    id: "26",
    homeTeam: { id: "NYJ", name: "Jets", abbreviation: "NYJ" },
    awayTeam: { id: "BUF", name: "Bills", abbreviation: "BUF" },
    startTime: "2023-11-19T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: 8 },
  },
  {
    id: "27",
    homeTeam: { id: "NE", name: "Patriots", abbreviation: "NE" },
    awayTeam: { id: "IND", name: "Colts", abbreviation: "IND" },
    startTime: "2023-11-12T13:00:00.000Z",
    status: "live",
    odds: { spread: -1 },
  },
  {
    id: "28",
    homeTeam: { id: "GB", name: "Packers", abbreviation: "GB" },
    awayTeam: { id: "LAC", name: "Chargers", abbreviation: "LAC" },
    startTime: "2023-11-12T16:25:00.000Z",
    status: "live",
    odds: { spread: 3.5 },
  },
  {
    id: "29",
    homeTeam: { id: "KC", name: "Chiefs", abbreviation: "KC" },
    awayTeam: { id: "PHI", name: "Eagles", abbreviation: "PHI" },
    startTime: "2023-11-20T20:15:00.000Z",
    status: "upcoming",
    odds: { spread: -2.5 },
  },
  {
    id: "30",
    homeTeam: { id: "BAL", name: "Ravens", abbreviation: "BAL" },
    awayTeam: { id: "CIN", name: "Bengals", abbreviation: "CIN" },
    startTime: "2023-11-16T20:15:00.000Z",
    status: "upcoming",
    odds: { spread: -4 },
  },
  {
    id: "31",
    homeTeam: { id: "SF", name: "49ers", abbreviation: "SF" },
    awayTeam: { id: "TB", name: "Buccaneers", abbreviation: "TB" },
    startTime: "2023-11-19T16:05:00.000Z",
    status: "upcoming",
    odds: { spread: -11 },
  },
  {
    id: "32",
    homeTeam: { id: "DAL", name: "Cowboys", abbreviation: "DAL" },
    awayTeam: { id: "CAR", name: "Panthers", abbreviation: "CAR" },
    startTime: "2023-11-19T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -10.5 },
  },
  {
    id: "33",
    homeTeam: { id: "PHI", name: "Eagles", abbreviation: "PHI" },
    awayTeam: { id: "BUF", name: "Bills", abbreviation: "BUF" },
    startTime: "2023-11-26T16:25:00.000Z",
    status: "upcoming",
    odds: { spread: -3.5 },
  },
  {
    id: "34",
    homeTeam: { id: "MIA", name: "Dolphins", abbreviation: "MIA" },
    awayTeam: { id: "NYJ", name: "Jets", abbreviation: "NYJ" },
    startTime: "2023-11-24T12:30:00.000Z",
    status: "upcoming",
    odds: { spread: -9.5 },
  },
  {
    id: "35",
    homeTeam: { id: "DET", name: "Lions", abbreviation: "DET" },
    awayTeam: { id: "GB", name: "Packers", abbreviation: "GB" },
    startTime: "2023-11-23T12:30:00.000Z",
    status: "upcoming",
    odds: { spread: -7 },
  },
  {
    id: "36",
    homeTeam: { id: "WAS", name: "Commanders", abbreviation: "WAS" },
    awayTeam: { id: "DAL", name: "Cowboys", abbreviation: "DAL" },
    startTime: "2023-11-23T16:30:00.000Z",
    status: "upcoming",
    odds: { spread: 7.5 },
  },
  {
    id: "37",
    homeTeam: { id: "SEA", name: "Seahawks", abbreviation: "SEA" },
    awayTeam: { id: "SF", name: "49ers", abbreviation: "SF" },
    startTime: "2023-11-23T20:20:00.000Z",
    status: "upcoming",
    odds: { spread: 3.5 },
  },
  {
    id: "38",
    homeTeam: { id: "MIN", name: "Vikings", abbreviation: "MIN" },
    awayTeam: { id: "CHI", name: "Bears", abbreviation: "CHI" },
    startTime: "2023-11-27T20:15:00.000Z",
    status: "upcoming",
    odds: { spread: -3 },
  },
  {
    id: "39",
    homeTeam: { id: "CIN", name: "Bengals", abbreviation: "CIN" },
    awayTeam: { id: "PIT", name: "Steelers", abbreviation: "PIT" },
    startTime: "2023-11-26T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -5 },
  },
  {
    id: "40",
    homeTeam: { id: "IND", name: "Colts", abbreviation: "IND" },
    awayTeam: { id: "TB", name: "Buccaneers", abbreviation: "TB" },
    startTime: "2023-11-26T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -1.5 },
  },
  {
    id: "41",
    homeTeam: { id: "JAX", name: "Jaguars", abbreviation: "JAX" },
    awayTeam: { id: "HOU", name: "Texans", abbreviation: "HOU" },
    startTime: "2023-11-26T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -4 },
  },
  {
    id: "42",
    homeTeam: { id: "NO", name: "Saints", abbreviation: "NO" },
    awayTeam: { id: "ATL", name: "Falcons", abbreviation: "ATL" },
    startTime: "2023-11-26T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: -5.5 },
  },
  {
    id: "43",
    homeTeam: { id: "NYG", name: "Giants", abbreviation: "NYG" },
    awayTeam: { id: "NE", name: "Patriots", abbreviation: "NE" },
    startTime: "2023-11-26T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: 3.5 },
  },
  {
    id: "44",
    homeTeam: { id: "LAC", name: "Chargers", abbreviation: "LAC" },
    awayTeam: { id: "BAL", name: "Ravens", abbreviation: "BAL" },
    startTime: "2023-11-26T20:20:00.000Z",
    status: "upcoming",
    odds: { spread: 3 },
  },
  {
    id: "45",
    homeTeam: { id: "DEN", name: "Broncos", abbreviation: "DEN" },
    awayTeam: { id: "CLE", name: "Browns", abbreviation: "CLE" },
    startTime: "2023-11-26T16:05:00.000Z",
    status: "upcoming",
    odds: { spread: -2.5 },
  },
  {
    id: "46",
    homeTeam: { id: "CHI", name: "Bears", abbreviation: "CHI" },
    awayTeam: { id: "MIN", name: "Vikings", abbreviation: "MIN" },
    startTime: "2023-12-03T13:00:00.000Z",
    status: "upcoming",
    odds: { spread: 4 },
  },
  {
    id: "47",
    homeTeam: { id: "GB", name: "Packers", abbreviation: "GB" },
    awayTeam: { id: "KC", name: "Chiefs", abbreviation: "KC" },
    startTime: "2023-12-03T20:20:00.000Z",
    status: "upcoming",
    odds: { spread: 6 },
  },
  {
    id: "48",
    homeTeam: { id: "ARI", name: "Cardinals", abbreviation: "ARI" },
    awayTeam: { id: "LAR", name: "Rams", abbreviation: "LAR" },
    startTime: "2023-12-03T16:05:00.000Z",
    status: "upcoming",
    odds: { spread: 5.5 },
  },
  {
    id: "49",
    homeTeam: { id: "LV", name: "Raiders", abbreviation: "LV" },
    awayTeam: { id: "KC", name: "Chiefs", abbreviation: "KC" },
    startTime: "2023-11-26T13:00:00.000Z",
    status: "live",
    odds: { spread: 8.5 },
  },
  {
    id: "50",
    homeTeam: { id: "PIT", name: "Steelers", abbreviation: "PIT" },
    awayTeam: { id: "CLE", name: "Browns", abbreviation: "CLE" },
    startTime: "2023-11-19T13:00:00.000Z",
    status: "completed",
    odds: { spread: -1 },
  },
];
